# .travis.yml

dist: trusty
sudo: false
language: node_js
node_js:
    - 6.11.1

addons:
apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable
        - google-chrome-beta

services:
    - mysql

before_install:
    # Set npm version to 5.3.0
    - npm i -g npm@5.3.0
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # Run db script file to create and populate database
    - mysql -u root --password="" < patientPortalDB.sql
  
install:
    # Install Frontend Dependencies
    - npm install -g angular-cli
    - npm install -g karma
    - npm install ./client
    - ng build ./client
    # Install Backend Dependencies
    - npm install ./server

script:
    # Frontend build
    - karma start ./client/karma.conf.js --single-run
    # Backend build
    - cd server
    - npm run intTest ./server -s && npm run unitTest -s,
    
